"""init
Revision ID: 43c3ba015ac4
Revises: 
Create Date: 2025-12-03 22:33:43.567951
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '43c3ba015ac4'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
def upgrade():
    # This initial revision is a baseline; DB schema should already match models.
    # If you want Alembic to create tables, replace this body with autogenerated operations.
    pass


def downgrade():
    # No downgrade for baseline
    pass
